package LC301_600;

public class LC389_FindtheDifference {
    /**
     * You are given two strings s and t.
     *
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     *
     * Return the letter that was added to t.
     *
     * Input: s = "abcd", t = "abcde"
     * Output: "e"
     *
     * Constraints:
     *
     * 0 <= s.length <= 1000
     * t.length == s.length + 1
     * s and t consist of lower-case English letters.
     * @param s
     * @param t
     * @return
     */
    // S1
    // time = O(m + n), space = O(1)
    public char findTheDifference(String s, String t) {
        int[] freq = new int[26];
        for (char c : s.toCharArray()) {
            freq[c - 'a']++;
        }

        for (char c : t.toCharArray()) {
            freq[c - 'a']--;
            if (freq[c - 'a'] < 0) return c;
        }
        return '\0';
    }

    // S2: bit
    // time = O(m + n), space = O(1)
    public char findTheDifference2(String s, String t) {
        char res = 0;
        for (char c : s.toCharArray()) res ^= c;
        for (char c : t.toCharArray()) res ^= c;
        return res;
    }
}
